# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

# config from Jonas Blum
# runtime: java

# automatic_scaling:
#      max_num_instances: 1

# runtime_config:
#      operating_system: "ubuntu22"
#      runtime_version: "17"

runtime: java17
env: flex
instance_class: B8

# automatic_scaling:
#   max_num_instances: 1
